python eval_sts.py \
    --eval_instance local \
    --pretrained_dir path-to-your-ckpt-for-evaluation \
    --path_sts path-to-the-senteval-datasets \
    --pdataname nli_train_posneg \
    --mode pairsupcon \
    --bert bertbase \
    --contrast_type HardNeg \
    --temperature 0.05 \
    --beta 1 \
    --lr 5e-06 \
    --lr_scale 100 \
    --p_batchsize 1024 \
    --pretrain_epoch 3 \
    --eval_epoch 3 \
    --seed 0 \
    --pseed 0 \
    --device_id 0 